from math import *
from turtle import *
def lum(a,b):
  hideturtle()
  speed(1000)
  goto(-200,0)
  pendown()
  pensize(1)
  forward(400)
  goto(0,0)
  setheading(90)
  for i in range(25):
    forward(4)
    penup()
    forward(4)
    pendown()
  penup()
  goto(0,0)
  setheading(270)
  for i in range(25):
    pendown()
    forward(4)
    penup()
    forward(4)
    pendown()
  penup()
  goto(0,0)
  setheading(90)
  left(a)
  pendown()
  color('red')
  pensize(2)
  forward(200)
  goto(0,0)
  setheading(270)
  left(b)
  forward(200)
  goto(0,0)
  setheading(90)
  right(a)
  forward(200)    
  penup()
  goto(-150,-110)
  write("i2=")
  goto(-120,-110)
  write(str(b))
  goto(-150,-90)
  write("i1=")
  goto(-120,-90)
  write(str(a))
