name: Upload submitted files

on:
  push:
    branches: [ main ]

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: submitted-files
        path: submitted-files

